# Cucumber shares RSpec's factories and support modules so both suites describe
# the same domain fixtures. env.rb (generated by cucumber-rails) has already
# loaded the Rails application by the time support files run, which is also when
# factory_bot_rails has loaded spec/factories.rb.
require Rails.root.join("spec/support/factory_bot")
require Rails.root.join("spec/support/csv_helpers")
require Rails.root.join("spec/support/api_response_helpers")
require Rails.root.join("spec/support/audit_helpers")
require Rails.root.join("spec/support/active_job_helpers")
require Rails.root.join("spec/support/s3_fake")

# factory_bot_rails wires this up for RSpec example groups; a Cucumber World has
# to be given the same syntax explicitly.
World(FactoryBot::Syntax::Methods)
World(CsvHelpers)
World(ApiResponseHelpers)
World(AuditHelpers)
World(ActiveJobHelpers)
World(S3TestDouble)
