require "rspec/mocks"

# Database isolation.
#
# `features/support/env.rb` is generated by cucumber-rails and calls
# `DatabaseCleaner.strategy = :transaction`. Under database_cleaner-core 2.x
# that assignment is a no-op: `Cleaners#strategy=` only updates cleaners that
# have already been registered, and none has been. A later
# `DatabaseCleaner.start` / `.clean` then iterates an empty collection, so no
# transaction is ever opened and every scenario commits its records. That leaks
# rows between scenarios and eventually trips the unique indexes on
# `employees.email` and `salary_records.employee_id/effective_date`.
#
# `database_cleaner-active_record` is `require: false` in the Gemfile, so
# nothing registers the ActiveRecord cleaner. Requiring it here is what runs the
# adapter's `ActiveSupport.on_load(:active_record)` block, which requires the
# strategy classes and registers a `:transaction` cleaner for ActiveRecord.
#
# Note that calling `DatabaseCleaner[:active_record].strategy = :transaction`
# directly does not work: the cleaner is created lazily, and resolving
# `:transaction` before the adapter has defined
# `DatabaseCleaner::ActiveRecord::Transaction` falls through to
# `::ActiveRecord::Transaction`, whose constructor rejects being called with no
# arguments.
#
# This file loads after `env.rb` but before any scenario runs, so
# cucumber-rails' own `Before`/`After` hooks (which call `start`/`clean`) pick
# the cleaner up.
require "database_cleaner/active_record"

# Scenario-level setup.
#
# rspec-mocks is normally wired up by the RSpec runner. Cucumber does not do it,
# so it is registered here instead, which is what lets scenarios stub the AWS
# SDK client and assert on application internals when a behaviour is easier to
# pin down that way.
World(RSpec::Mocks::ExampleMethods)

Before do
  RSpec::Mocks.setup
  # Scenarios are rolled back, so generated values start from the beginning
  # again; uploaded files and job queues are not transactional.
  FactoryBot.rewind_sequences
  ReferenceData.reset!
  reset_scenario_state!
  reset_job_queues!


  # Every route of this API is behind a token, and every scenario is written from
  # the HR Manager's point of view, so the scenario is signed in once here. The
  # header comes from `AuthenticationHelpers` (features/support/api_authentication.rb),
  # the same helper the RSpec request specs use, so a scenario and a request spec
  # authenticate identically.
  auth_headers.each { |name, value| header name, value }
end

# Uploaded CSVs are Active Storage blobs on the test disk service, and a file is
# not part of the transaction DatabaseCleaner rolls back. Destroying the blobs
# after each scenario keeps tmp/storage from growing over a run.
After do
  purge_test_blobs!
end

After do
  RSpec::Mocks.verify
end
